apiVersion: v1
kind: Service
metadata:
  name: {{ include "isaacchart.fullname" . }}
  labels:
    {{- include "isaacchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "isaacchart.selectorLabels" . | nindent 4 }}
